### ISSUE TITLE
Namespace packages cause KeyError 'sitedir' when running the generated launcher

### ISSUE THREAD

**Issue by henryborchers** [zsquareplusc/python-embedded-launcher#7]
I love this project. It does exactly what I want, create a standalone Python application, packages my deps, and generate portable .exe entry points that don't break when I relocate the directory.  This lets me make my own installer package afterwards exactly how I want it. 

Awesome stuff!!

However, I just tried using it on a large project and I got an error when I tried to run the generated launcher exe. 

C:\Users\hborcher\PycharmProjects\Hathi_Submission_Workflow\dist\launcher3-64>bin\hsw.exe
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Users\hborcher\PycharmProjects\Hathi_Submission_Workflow\dist\launcher3-64\bin\hsw.exe\__main__.py", line 6, in <module>
  File "C:\Users\hborcher\PycharmProjects\Hathi_Submission_Workflow\dist\launcher3-64\bin\hsw.exe\launcher.py", line 66, in patch_sys_path
  File "C:\Users\hborcher\PycharmProjects\Hathi_Submission_Workflow\dist\launcher3-64\bin\hsw.exe\launcher.py", line 45, in process_pth_file
  File "<string>", line 1, in <module>
KeyError: 'sitedir'

I'm not sure which pth file is causing the trouble and I'm trying to debug an error but I'm not exactly sure how.

**Comment by henryborchers** [comment]
okay it looks like it's caused by using a namespace package like ruamel.yaml. When pip installs the namespace package to the Lib\site-packages directory, it generates a .pth file for redirecting. It's here that the launcher.py keeps failing at process_pth_file().

**Comment by zsquareplusc** [comment]
can you post the contents of the offending pth file? where does it expect to find `sitedir`?

as for debugging:
the embedded launcher.py is [here](https://github.com/zsquareplusc/python-embedded-launcher/blob/master/launcher_tool/launcher.py) you could add a print statement to the loop in `process_pth_file()`. if such problems occur repeatedly, a debug statement could be included in the module, and maybe controlled via environment variable or special build of the exe.

**Comment by henryborchers** [comment]
Hi @zsquareplusc! Thanks for replying. Thanks for the tip on debugging.

I created a sample project that replicated what I did. Hopefully this helps and you can do something about it because I love your project.

https://github.com/henryborchers/test-python-embedded-launcher

**Comment by henryborchers** [comment]
I've been able to replicate the error with the pth file using two namespace packages, ruamel.yaml and one of my own on a private index.

**Comment by zsquareplusc** [comment]
thanks for the example code.

great... they access a local variable of the caller... (in that pth file)
`p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('ruamel',))`

**Comment by henryborchers** [comment]
Namespace packages aren’t very common but they do show up now and then. I hope the sample code helps.

**Comment by zsquareplusc** [comment]
I've pushed a change that should fix the issue (worked to run your example). it adds that local variable with the directory of the pth file as contents.

**Comment by henryborchers** [comment]
Awesome! I'm excited to try this out. However, I'm currently unable to test this because I cannot build from source due to not having Python 2.7 installed (and I REALLLY don't want to install it). Is it possible for me to build only a Python 3 version from source or can you distribute a whl?

**Comment by zsquareplusc** [comment]
I do not think that you need Python 2 for anything here.

you could `pip install https://github.com/zsquareplusc/python-embedded-launcher/archive/master.zip` in a (Python 2 or 3) virtualenv and copy the launcher.exe's from the other installation, they have not changed.

**Comment by henryborchers** [comment]
That seems to work! Nice job.  Any chance you'll be able to upload a new version the PyPI soon so that I can simply pip install it?
